{
    "allrecipes.com": {
        "ads": 3,
        "below fold": true,
        "domain": "allrecipes.com",
        "font family": "Verdana, Arial, sans-serif",
        "font size": 10.6666669845581,
        "html5": false,
        "images": 94,
        "liked": false,
        "main image": 69696,
        "off site links": 94
    },
    "annabel-langbein.com": {
        "ads": 0,
        "below fold": true,
        "domain": "annabel-langbein.com",
        "font family": "nimbus-sans, Arial, Helvetica, sans-serif",
        "font size": 15,
        "html5": true,
        "images": 3,
        "liked": true,
        "main image": 297732,
        "off site links": 10
    },
    "chow.com": {
        "ads": 3,
        "below fold": false,
        "domain": "chow.com",
        "font family": "proxima-nova, sans-serif",
        "font size": 20,
        "html5": true,
        "images": 17,
        "liked": true,
        "main image": 1091840,
        "off site links": 40
    },
    "cookinglight.com": {
        "ads": 3,
        "below fold": true,
        "domain": "cookinglight.com",
        "font family": "Arial, 'Helvetica Neue', Helvetica, sans-serif",
        "font size": 12,
        "html5": true,
        "images": 45,
        "liked": false,
        "main image": 160000,
        "off site links": 57
    },
    "food.com": {
        "ads": 2,
        "below fold": true,
        "domain": "food.com",
        "font family": "TensoLight, 'Helvetica Neue', Helvetica, Arial, sans-serif",
        "font size": 16,
        "html5": true,
        "images": 31,
        "liked": true,
        "main image": 230880,
        "off site links": 70
    },
    "foodnetwork.com": {
        "ads": 2,
        "below fold": true,
        "domain": "foodnetwork.com",
        "font family": "'Lucida Grande', Helvetica, Arial, sans-serif",
        "font size": 13,
        "html5": true,
        "images": 93,
        "liked": false,
        "main image": 123525,
        "off site links": 139
    },
    "jamieoliver.com": {
        "ads": 3,
        "below fold": true,
        "domain": "jamieoliver.com",
        "font family": "Courier, 'Courier New', monospace",
        "font size": 13,
        "html5": true,
        "images": 47,
        "liked": true,
        "main image": 245437.9375,
        "off site links": 46
    },
    "kraftrecipes.com": {
        "ads": 10,
        "below fold": false,
        "domain": "kraftrecipes.com",
        "font family": "'Trebuchet MS', Arial",
        "font size": 14,
        "html5": false,
        "images": 116,
        "liked": false,
        "main image": 16146,
        "off site links": 45
    },
    "marthastewart.com": {
        "ads": 2,
        "below fold": true,
        "domain": "marthastewart.com",
        "font family": "Georgia, serif",
        "font size": 14,
        "html5": true,
        "images": 87,
        "liked": false,
        "main image": 136290,
        "off site links": 47
    },
    "myrecipes.com": {
        "ads": 13,
        "below fold": true,
        "domain": "myrecipes.com",
        "font family": "'Helvetica Neue', Arial, Helvetica, Geneva, sans-serif",
        "font size": 13,
        "html5": true,
        "images": 69,
        "liked": false,
        "main image": 90000,
        "off site links": 268
    },
    "recipes.co.nz": {
        "ads": 0,
        "below fold": true,
        "domain": "recipes.co.nz",
        "font family": "Oxygen, Arial, 'Sans-serif regular'",
        "font size": 15,
        "html5": true,
        "images": 26,
        "liked": true,
        "main image": 266340,
        "off site links": 10
    },
    "seriouseats.com": {
        "ads": 3,
        "below fold": true,
        "domain": "seriouseats.com",
        "font family": "ff-tisa-web-pro, Georgia, Times, serif",
        "font size": 16,
        "html5": true,
        "images": 50,
        "liked": true,
        "main image": 283207.5,
        "off site links": 80
    },
    "simplyrecipes.com": {
        "ads": 4,
        "below fold": true,
        "domain": "simplyrecipes.com",
        "font family": "open-sans, Helvetica, Arial, sans-serif",
        "font size": 14,
        "html5": true,
        "images": 99,
        "liked": true,
        "main image": 180440,
        "off site links": 20
    },
    "taste.com.au": {
        "ads": 5,
        "below fold": true,
        "domain": "taste.com.au",
        "font family": "Museo-300, Arial, Helvetica, sans-serif",
        "font size": 14,
        "html5": true,
        "images": 81,
        "liked": false,
        "main image": 239200,
        "off site links": 73
    },
    "tasteofhome.com": {
        "ads": 3,
        "below fold": true,
        "domain": "tasteofhome.com",
        "font family": "Arial, 'Helvetica Neue', Helvetica, sans-serif",
        "font size": 14,
        "html5": true,
        "images": 49,
        "liked": false,
        "main image": 91204,
        "off site links": 98
    }
}
